mos_15N = [
    ["552-809-1005", "RESTORE AIRCRAFT WIRING",
        "Reviewed aircraft forms and records IAW DA PAM 738-751 and ULLS-A(E)",
        "Inspected aircraft before power is applied to ensure safety of personnel and equipment.",
        "Applied electrical power to the aircraft IAW applicable TM",
        "Performed system operational check IAW applicable TM",
        "Performed troubleshooting procedures IAW applicable TM",
        "Performed maintenance procedures for the identified fault IAW applicable TM",
        "Performed maintenance operational checks to verify system is restored and operates to required specification IAW applicable aircraft TM",
        "Removed electrical power from the aircraft IAW applicable TM",
        "Performed follow on maintenance in accordance with applicable TM",
        "a. Accounted for and stored tools and equipment",
        "b. Updated forms and records in accordance with DA PAM 738-751",
        "c. Performed Foreign Object Damage/Debris (FOD) check",
        "d. Requested a Technical Inspector (TI) as required"
     ],
    [
        "552-809-1006", "REPAIR DATA BUS CONNECTORS",
        "Reviewed aircraft forms and records IAW DA PAM 738-751 and ULLS-A(E)",
        "Inspected aircraft before power is applied to ensure safety of personnel and equipment",
        "Applied electrical power to the aircraft in accordance with applicable aircraft TM (EM 0284 for a UH-60M or EM 0281 for a CH-47F) and EM 0171.",
        "Performed system operational check of the CH-47F 1553B Data Bus IAW EM 0281. (See step 5 for UH-60M).",
        "a. Performed Test Set Charging Procedure.",
        "b. Performed Test Set Power on Check Procedure.",
        "c. Performed Test Set Calibration Procedure.",
        "d. Performed Data Bus Network Troubleshooting Procedures-Set-up Procedure.",
        "e. Performed Normal Transmission (Signal Line/Insertion Loss) Test Procedure.",
        "f. Performed Bus Shield Test Procedure.",
        "g. Performed Stub Shield Test.",
        "Performed system operational check of the UH-60M 1553B Data Bus System IAW EM 0284.",
        "a. Performed Status Check Procedure.",
        "b. Performed Data BUS A Operational Check Procedure.",
        "c. Performed BUS B Operational Check.",
        "Performed troubleshooting procedures for the 1553B Data Bus System IAW applicable aircraft TM (EM0284 for a UH-60M or EM 0281 for a CH-47F).",
        "Performed maintenance procedures for the identified fault within the 1553b Data Bus System IAW applicable aircraft TM (EM 0284 for a UH-60M or EM 0281 for a CH-47F).",
        "Repaired the 1553B Data Bus wiring IAW applicable aircraft TM (EM 0284 for a UH-60M or EM 0281 for a CH-47F).",
        "Performed maintenance operational check of the 1553B Data Bus System to verify system operates to required specification IAW applicable aircraft TM (EM 0284 for a UH-60M or EM 0281 for a CH-47F).",
        "Removed electrical power from the aircraft IAW applicable aircraft TM (EM 0284 for a UH-60M or EM 0281 for a CH-47F).",
        "Performed follow on maintenance IAW applicable TM",
        "a. Accounted for and store tools and equipment IAW Unit SOP and DOD6050.5W.",
        "b. Updated forms and records in accordance with DA PAM 738-751.",
        "c. Performed Foreign Object Debris/Damage (FOD) check IAW DOD6050.5W.",
        "d. Requested a Technical Inspector (TI) as required."
    ],
    [
        "552-811-1002", "RESTORE RADIO SET AN/ARC 164 (*) (UHF) SYSTEM (*)",
        "Reviewed aircraft forms and records IAW DA PAM 738-751 and ULLS-A(E).",
        "Inspected aircraft before power is applied to ensure safety of personnel and equipment.",
        "Applied electrical power to the aircraft IAW applicable TM. *",
        "Performed system operational check IAW applicable TM.",
        "Performed troubleshooting procedures IAW applicable TM.",
        "Performed maintenance procedures for the identified fault IAW applicable TM.",
        "Performed maintenance operational checks to verify system is restored and operates to required specification IAW applicable aircraft TM.",
        "Removed electrical power from the aircraft IAW applicable TM. *",
        "Performed follow on maintenance in accordance with applicable TM.",
        "a. Accounted for and stored tools and equipment.",
        "b. Updated forms and records in accordance with DA PAM 738-751.",
        "c. Performed Foreign Object Damage/Debris (FOD) check.",
        "d. Requested a Technical Inspector (TI) as required."
    ],
    [
        "552-811-1005", "RESTORE CONTROL DISPLAY UNIT (CDU) (CH-47F)",
        "Reviewed aircraft forms and records IAW DA PAM 738-751 and ULLS-A(E).",
        "Inspected aircraft before power is applied to ensure safety of personnel and equipment.",
        "Applied electrical power to the aircraft in accordance with applicable TM.",
        "Performed system operation check of the Control Display Unit (CDU), IAW applicable aircraft TM.",
        "a. Performed Control Display Units (CDU) Operational Check Operational Checkout Test Procedures.",
        "b. Performed CAAS Preparation Operational Checkout Test Procedures.",
        "c. Performed Avionics Summary Test Operational Checkout Test Procedures.",
        "d. Performed NVG Lighting Test Operational Checkout Test Procedures.",
        "e. Performed I/O Test Operational Checkout Test Procedures.",
        "f. Performed Self Test Operational Checkout Test Procedures.",
        "g. Performed Boresight Data Entry Operational Checkout Test Procedures.",
        "h. Performed CDU Bus Controller/Remote Terminal Test Operational Checkout Test Procedures.",
        "Performed troubleshooting procedures for the Control Display Unit (CDU), IAW applicable aircraft TM.",
        "Performed maintenance procedures for the identified fault within the Control Display Unit (CDU), IAW applicable TM.",
        "Performed maintenance operational check of the Control Display Unit (CDU) to verify system operates to required specification IAW applicable TM.",
        "Removed electrical power from the aircraft IAW applicable TM.",
        "Performed follow on maintenance in accordance with applicable references.",
        "a. Accounted for and stored tools and equipment IAW maintenance operations.",
        "b. Updated forms and records IAW aviation maintenance operations, unit policies and the applicable aircraft manuals, DA PAM 738-751, and ULLS-AE.",
        "c. Conducted a final FOD check/inspection of maintenance area IAW aviation maintenance operations, unit policies and the applicable aircraft manuals.",
        "d. Requested a Technical Inspector (TI) as required IAW maintenance operations, applicable aircraft manuals."
    ],
    [
        "552-811-1006", "RESTORE GENERAL PURPOSE PROCESSOR UNIT (GPPU) (CH-47F)",
        "Reviewed forms and records IAW DA PAM 738-751 and ULLS-A(E).",
        "Inspected aircraft before power is applied to ensure safety of personnel and equipment.",
        "Applied electrical power to the aircraft in accordance with applicable TM.",
        "Performed system operation check of the General Purpose Processor Units (GPPU), IAW applicable aircraft TM.",
        "a. Performed General Purpose Processor Units (GGPU) Operational Checkout Test Procedure.",
        "b. Performed GPPU No. 1 and No. 2 PSM and VPM - CAAS Preparation (GGPU) Operational Checkout Test Procedure.",
        "c. Performed Configuration Test Operational Checkout Procedure.",
        "d. Performed Avionics Summary Operational Checkout Test Procedure.",
        "e. Performed GPPU I/O Operational Checkout Test Procedure.",
        "f. Performed GPPU 1 Self Test Operational Checkout Procedure.",
        "g. Performed GPPU 2 Self Test Operational Checkout Procedure.",
        "h. Performed Digital Video Cable Test Operational Checkout Procedure.",
        "Performed troubleshooting procedures for the General Purpose Processor Units (GPPU), IAW applicable TM.",
        "Performed maintenance procedures for the identified fault within the General Purpose Processor Units (GPPU), IAW applicable TM.",
        "a. Repaired or replaced wires, terminal blocks, as required.",
        "b. Replaced LRUs as required.",
        "Performed maintenance operational check of the General Purpose Processor Units (GPPU) to verify system operates to required specification IAW applicable TM.",
        "Removed electrical power from the aircraft IAW applicable TM.",
        "Performed follow on maintenance in accordance with applicable references.",
        "a. Accounted for and stored tools and equipment IAW maintenance operations.",
        "b. Updated forms and records IAW aviation maintenance operations, unit policies and the applicable aircraft manuals, DA PAM 738-751, and ULLS-A(E).",
        "c. Conducted a final FOD check/inspection of maintenance area IAW aviation maintenance operations, unit policies and the applicable aircraft manuals.",
        "d. Requested a Technical Inspector (TI) as required IAW maintenance operations, applicable aircraft manuals."
    ],
    [
        "552-811-1017", "RESTORE DATA TRANSFER SYSTEM (*)",
        "Reviewed aircraft forms and records IAW DA PAM 738-751 and ULLS-A(E).",
        "Inspected aircraft before power is applied to ensure safety of personnel and equipment.",
        "Applied electrical power to the aircraft IAW applicable TM.",
        "Performed system operational check IAW applicable TM.",
        "Performed troubleshooting procedures IAW applicable TM.",
        "Performed maintenance procedures for the identified fault IAW applicable TM.",
        "Performed maintenance operational checks to verify system is restored and operates to required specification IAW applicable aircraft TM.",
        "Removed electrical power from the aircraft IAW applicable TM.",
        "Performed follow on maintenance in accordance with applicable TM.",
        "a. Accounted for and stored tools and equipment.",
        "b. Updated forms and records in accordance with DA PAM 738-751.",
        "c. Performed Foreign Object Damage/Debris (FOD) check.",
        "d. Requested a Technical Inspector (TI) as required."
    ],
    [
        "552-811-1103", "RESTORE DIGITAL INTERCOMMUNICATIONS SYSTEM (DICS) (*)",
        "Reviewed aircraft forms and records IAW DA PAM 738-751 and ULLS-A(E)",
        "Inspected aircraft before power is applied to insure safety of personnel and equipment.",
        "Applied electrical power to the aircraft in accordance with applicable TM",
        "Performed system operational check of the Digital Intercommunications System (DICS)IAW applicable aircraft TM .",
        "Performed troubleshooting procedures for the Digital Intercommunications System (DICS) IAW applicable TM",
        "Performed maintenance procedures for the identified fault within the Digital Intercommunications System (DICS) IAW applicable TM.",
        "Performed maintenance operational check of the Digital Intercommunications System (DICS) to verify system operates to required specification IAW applicable TM",
        "Removed electrical power from the aircraft IAW applicable TM",
        "Performed follow on maintenance IAW applicable references."
    ]
]