mos_15F =  [
    [
        "552-918-6001", "OPERATE THE AVIATION GROUND POWER UNIT (AGPU) (AVN)",
        "Reviewed aircraft forms and records IAW DA PAM 738-751 and ULLS-A(E).",
        "Inspected component to ensure safety of personnel and equipment.",
        "Performed operation check of the Aviation Ground Power Unit (AGPU) IAW applicable TM.",
        "Performed Start up procedures for the Aviation Ground Power Unit (AGPU)IAW applicable TM.",
        "Performed operation procedures for the Aviation Ground Power Unit (AGPU) IAW applicable TM.",
        "Performed shut down procedures for the Aviation Ground Power Unit (AGPU) IAW applicable TM.",
        "Performed Follow on Maintenance IAW applicable TM.",
        "a. Accounted for and stored tools and equipment.",
        "b. Updated forms and records in accordance with DA PAM 738-751.",
        "c. Performed Foreign Object Debris/Damage (FOD) Check."
    ],
    [
        "552-811-1704", "RESTORE DATA NETWORKS (*)",
        "Reviewed aircraft forms and records IAW DA PAM 738-751 and ULLS-A(E).",
        "Inspected aircraft before power is applied to ensure safety of personnel and equipment.",
        "Applied electrical power to the aircraft IAW applicable TM.",
        "Performed system operational check IAW applicable TM.",
        "Performed troubleshooting procedures IAW applicable TM.",
        "Performed maintenance procedures for the identified fault IAW applicable TM.",
        "Performed maintenance operational checks to verify system is restored and operates to required specification IAW applicable aircraft TM.",
        "Removed electrical power from the aircraft IAW applicable TM.",
        "Performed follow on maintenance in accordance with applicable TM.",
        "a. Accounted for and stored tools and equipment.",
        "b. Updated forms and records in accordance with DA PAM 738-751.",
        "c. Performed Foreign Object Damage/Debris (FOD) check.",
        "d. Requested a Technical Inspector (TI) as required."
    ],
    [
        "552-811-1557", "RESTORE SIGNAL DETECTOR SYSTEM AN/APR 39 (V)*",
        "Reviewed aircraft forms and records IAW DA PAM 738-751 and ULLS-A(E).",
        "Inspected aircraft before power is applied to ensure safety of personnel and equipment.",
        "Applied electrical power to the aircraft IAW applicable TM.",
        "Performed system operational check IAW applicable TM.",
        "Performed troubleshooting procedures IAW applicable TM.",
        "Performed maintenance procedures for the identified fault IAW applicable TM.",
        "Performed maintenance operational checks to verify system is restored and operates to required specification IAW applicable aircraft TM.",
        "Removed electrical power from the aircraft IAW applicable TM.",
        "Performed follow on maintenance in accordance with applicable TM.",
        "a. Accounted for and stored tools and equipment.",
        "b. Updated forms and records in accordance with DA PAM 738-751.",
        "c. Performed Foreign Object Damage/Debris (FOD) check.",
        "d. Requested a Technical Inspector (TI) as required."
    ],
    [
        "552-811-1348", "RESTORE EGI SET H-764GU (*)",
        "Reviewed aircraft forms and records IAW DA PAM 738-751 and ULLS-A(E).",
        "Inspected aircraft and equipment before power is applied to ensure safety of personnel and equipment IAW applicable TM.",
        "Applied electrical power to the aircraft in accordance with applicable TM.",
        "Performed system operation check of the EGI SET H-764GU IAW applicable aircraft TM.",
        "a. Performed No. 1 and No. 2 Embedded Global Positioning System Inertial Navigation Set (EGI)(UH-60M) operational check IAW IETM 0284.",
        "(1) Performed Setup Operational Checkout Test Procedure.",
        "(2) Performed EGI Alignment - Aircraft Location Operational Checkout Test Procedure.",
        "(3) Performed EGI Alignment - Auto Alignment Operational Checkout Test Procedure.",
        "(4) Performed EGI Alignment - Manual Alignment Operational Checkout Test Procedure.",
        "(5) Performed No.1 EGI Status Operational Checkout Test Procedure.",
        "(6) Performed No.1 EGI IBIT Operational Checkout Test Procedure.",
        "(7) Performed No.1 EGI MFD Interface Operational Checkout Test Procedure.",
        "(8) Performed No.2 EGI Status Operational Checkout Test Procedure.",
        "(9) Performed No.2 EGI IBIT Operational Checkout Test Procedure.",
        "(10) Performed No.2 EGI MFD Interface Operational Checkout Test Procedure.",
        "b. Performed the Dual Embedded Global Position System/Inertial Navigation System(ESIS)(CH-47F) operational check IAW IETM 0281.",
        "(1) Performed Setup Operational Checkout Test Procedure.",
        "(2) Performed Power On Control Operational Checkout Test Procedure.",
        "(3) Performed Backup Battery Operational Checkout Test Procedure.",
        "(4) Performed EGI Self-Test Operational Checkout Procedure.",
        "(5) Performed GPS Crypto Loader Test Operational Checkout Procedure.",
        "(6) Performed GPS Satellite Reception Test Operational Checkout Procedure.",
        "(7) Performed Acquiring Satellites Operational Checkout Test Procedure.",
        "Performed troubleshooting procedures for the EGI SET H-764GU IAW applicable TM.",
        "Performed maintenance procedures for the identified fault within the EGI SET H-764GU IAW applicable TM.",
        "Performed maintenance operational check of the EGI SET H-764GU to verify system operates to required specification IAW applicable TM.",
        "Removed electrical power from the aircraft IAW applicable TM.",
        "Performed follow on maintenance IAW applicable TM.",
        "a. Accounted for and stored tools and equipment IAW maintenance operations.",
        "b. Updated forms and records IAW aviation maintenance operations, unit policies and the applicable aircraft manuals, DA PAM 738-751, and ULLS-AE.",
        "c. Performed a final FOD check/inspection of maintenance area IAW aviation maintenance operations, unit policies and the applicable aircraft manuals.",
        "d. Requested a Technical Inspector (TI) as required IAW maintenance operations, applicable aircraft manuals."
    ],
    [
        "552-811-1311", "RESTORE DIGITAL MAP SYSTEM (CH-47F)",
        "Checked forms and records IAW DA PAM 738-751 and ULLS-AE.",
        "Inspected aircraft before power is applied to ensure safety of personnel and equipment.",
        "Applied electrical power to the aircraft in accordance with applicable TM.*",
        "Performed visual check of the DIGITAL MAP SYSTEM IAW applicable TM.",
        "Performed operational check of the DIGITAL MAP SYSTEM IAW applicable TM.",
        "Performed troubleshooting procedures for the DIGITAL MAP SYSTEM IAW applicable TM.",
        "Performed maintenance procedures for the identified fault within the DIGITAL MAP SYSTEM IAW applicable TM.",
        "Performed maintenance operational check of the DIGITAL MAP SYSTEM to verify system operates to required specification IAW applicable TM.",
        "Removed electrical power from the aircraft IAW applicable TM.*",
        "Performed follow on maintenance in accordance with applicable references.",
        "a. Accounted for and stored tools and equipment.",
        "b. Updated forms and records in accordance with DA PAM 738-751.",
        "c. Performed Foreign Object Damage/Debris (FOD) check.",
        "d. Requested a Technical Inspector (TI) as required."
    ]
]